'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class english_resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Assignment4.english resources", GetType(english_resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exit.
    '''</summary>
    Friend Shared ReadOnly Property _Exit() As String
        Get
            Return ResourceManager.GetString("Exit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to american flag.gif.
    '''</summary>
    Friend Shared ReadOnly Property Flag() As String
        Get
            Return ResourceManager.GetString("Flag", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MIRRORING EXAMPLE.
    '''</summary>
    Friend Shared ReadOnly Property FormTitle() As String
        Get
            Return ResourceManager.GetString("FormTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Maybe.
    '''</summary>
    Friend Shared ReadOnly Property Maybe() As String
        Get
            Return ResourceManager.GetString("Maybe", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You chose Maybe.
    '''</summary>
    Friend Shared ReadOnly Property MaybeMessage() As String
        Get
            Return ResourceManager.GetString("MaybeMessage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No.
    '''</summary>
    Friend Shared ReadOnly Property No() As String
        Get
            Return ResourceManager.GetString("No", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You chose No.
    '''</summary>
    Friend Shared ReadOnly Property NoMessage() As String
        Get
            Return ResourceManager.GetString("NoMessage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Yes.
    '''</summary>
    Friend Shared ReadOnly Property Yes() As String
        Get
            Return ResourceManager.GetString("Yes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You chose Yes.
    '''</summary>
    Friend Shared ReadOnly Property YesMessage() As String
        Get
            Return ResourceManager.GetString("YesMessage", resourceCulture)
        End Get
    End Property
End Class
